### ISSUE TITLE
mvn package error

### ISSUE THREAD

**Issue by 362228416** [quarkiverse/quarkiverse-mybatis#19]
I just introduce a dependency and the compilation will fail, and it's important to me what configuration I need to do to compile

```bash
./mvnw clean package -Dmaven.test.skip=true -Dnative  
```

pom.xml
```xml
<properties>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
    <maven.compiler.target>11</maven.compiler.target>
    <quarkus.platform.version>1.10.5.Final</quarkus.platform.version>
    <maven.compiler.source>11</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <quarkus-plugin.version>1.10.5.Final</quarkus-plugin.version>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
  </properties>
```

```bash
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.reflect.Class_getEnclosingMethod0_8a7a0562f19e413046b2404928996c9b00e4e19e.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
        parsing java.lang.reflect.Method.invoke(Method.java:566)
        parsing io.quarkus.arc.impl.Qualifiers.invoke(Qualifiers.java:100)
        parsing io.quarkus.arc.impl.Qualifiers.hasQualifier(Qualifiers.java:61)
        parsing io.quarkus.arc.impl.Qualifiers.hasQualifiers(Qualifiers.java:38)
        parsing io.quarkus.arc.impl.ArcContainerImpl.matches(ArcContainerImpl.java:755)
        parsing io.quarkus.arc.impl.ArcContainerImpl.getMatchingBeans(ArcContainerImpl.java:627)
        parsing io.quarkus.arc.impl.ArcContainerImpl.getBeans(ArcContainerImpl.java:468)
        parsing io.quarkus.arc.impl.BeanManagerImpl.getBeans(BeanManagerImpl.java:95)
        parsing io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:102)
        parsing io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        parsing io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        parsing io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        parsing io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:331)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.getEnclosingMethod0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:404)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:384)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:76)
        at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:93)
        at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
        at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:39)
        at com.oracle.svm.reflect.hosted.ReflectionSubstitutionType$ReflectiveInvokeMethod.buildGraph(ReflectionSubstitutionType.java:536)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:333)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:187)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        ... 13 more
Error: Image build request failed with exit status 1
```

**Comment by zhfeng** [comment]
@362228416 I think you need to add
```
<quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime</quarkus.native.additional-build-args>
```
in the native profile right now.

and yeah, I hope to remove this option in the future release.

**Comment by 362228416** [comment]
thanks, 
mybatis mapUnderscoreToCamelCase how to set ?

**Comment by zhfeng** [comment]
sorry, I'm not similar with the mybatis. Can you provide more detail about this problem ? Anyway, it should be better to create a new issue for mapUnderscoreToCamelCase.

**Comment by 362228416** [comment]
我现在打包native成功了，但是在jvm下运行没有问题的代码，native会有问题，出现找不到构造器的问题

Caused by: org.apache.ibatis.executor.ExecutorException: No constructor found in com.xx.model.User matching [java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createByConstructorSignature(DefaultResultSetHandler.java:701)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createResultObject(DefaultResultSetHandler.java:657)


我的model里面添加了默认构造器，已经全部参数的构造器，也还是不行，参数类型配置都是跟异常打印出来的匹配得上，不知道什么原因

public User() {
}

public User(Integer id, String username, String nickname, String password, String mobile, Integer status, Timestamp createTime, Timestamp updateTime, Timestamp lastLoginTime) {
    this.id = id;
    this.username = username;
    this.nickname = nickname;
    this.password = password;
    this.mobile = mobile;
    this.status = status;
    this.createTime = createTime;
    this.updateTime = updateTime;
    this.lastLoginTime = lastLoginTime;
}

最后，这个库是在只能运行jvm上面用的吗，还是可以打成native，native的话需要什么配置吗？

**Comment by 362228416** [comment]
@zhfeng

**Comment by zhfeng** [comment]
@362228416 please create a new issue and provide these information and simple reproducer would be very helpful !

**Comment by zhfeng** [comment]
Although I can read chinese, it could be better to describe it with English which could help more people with the same issue.
