### ISSUE TITLE
No constructor found 

### ISSUE THREAD

**Issue by 362228416** [quarkiverse/quarkiverse-mybatis#20]
The JVM is running without problems. Native will report an error

```bash
Caused by: org.apache.ibatis.executor.ExecutorException: No constructor found in com.xx.model.User matching [java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp]
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createByConstructorSignature(DefaultResultSetHandler.java:701)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createResultObject(DefaultResultSetHandler.java:657)
```

I added a default constructor and a full-parameter constructor to my model, but it still doesn't work. The parameter type configuration matches the one printed by the exception. I don't know why

```java
public User() {
}

public User(Integer id, String username, String nickname, String password, String mobile, Integer status, Timestamp createTime, Timestamp updateTime, Timestamp lastLoginTime) {
this.id = id;
this.username = username;
this.nickname = nickname;
this.password = password;
this.mobile = mobile;
this.status = status;
this.createTime = createTime;
this.updateTime = updateTime;
this.lastLoginTime = lastLoginTime;
}
```

Finally, does this library run on JVM only, or can it be called native? Is there any configuration required for native?

**Comment by zhfeng** [comment]
Thanks @362228416 for reporting this issue.

Is it possible to provide a simple project to reproduce this issue ? Or you can provide some steps I can follow to reproduce it.
So I can take a close look.

**Comment by 362228416** [comment]
@zhfeng 

test on linux
step:
1、git clone https://github.com/362228416/quarkus-mybatis-demo.git
2、create database and import db.sql
3、./mvnw clean package -Dmaven.test.skip=true -Dnative
4、./target/quarkus-mybatis-demo-1.0.0-SNAPSHOT-runner
5、curl http://localhost:8080/users
6、curl http://localhost:8080/users/save?username=zhangsan&password=123456

**Comment by 362228416** [comment]
### Error updating database.  Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'username' in 'class com.cs.model.User'
### The error may exist in com/cs/dao/UserMapper.java (best guess)
### The error may involve com.cs.dao.UserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: insert into user(username,password) values(?,?)
### Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'username' in 'class com.cs.model.User'
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:136)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:40)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.apache.ibatis.exceptions.PersistenceException:

**Comment by 362228416** [comment]
```bash
### Error querying database.  Cause: org.apache.ibatis.executor.ExecutorException: No constructor found in com.cs.model.User matching [java.lang.Integer, java.lang.String, java.lang.String]
### The error may exist in com/cs/dao/UserMapper.java (best guess)
### The error may involve com.cs.dao.UserMapper.findAll
### The error occurred while handling results
### SQL: select id, username, password from user
### Cause: org.apache.ibatis.executor.ExecutorException: No constructor found in com.cs.model.User matching [java.lang.Integer, java.lang.String, java.lang.String]
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:357)
        at com.sun.proxy.$Proxy282.selectList(Unknown Source)
        at org.apache.ibatis.session.SqlSessionManager.selectList(SqlSessionManager.java:206)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy247.findAll(Unknown Source)
        at com.cs.web.UserController.users(UserController.java:18)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 19 more
Caused by: org.apache.ibatis.executor.ExecutorException: No constructor found in com.cs.model.User matching [java.lang.Integer, java.lang.String, java.lang.String]
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createByConstructorSignature(DefaultResultSetHandler.java:701)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createResultObject(DefaultResultSetHandler.java:657)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.createResultObject(DefaultResultSetHandler.java:630)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:397)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
```

**Comment by 362228416** [comment]
I have found the problem, it is the problem of MyBatis. In addition, I need to add a reflection configuration file, and it is OK to add all the model classes used

**Comment by zhfeng** [comment]
It is great to hear this. And I think it could be very useful to provide your solution, e.g. how to add the model classes in the reflection configuration file. These information will help more people when they met the similar problems. Thanks in adavance !

Also, I think there is some room we can improve the mybatis extension for these reflection issues.

1. Provide a preporty such as **quarkus.mybatis.models** in the appliaction.properties.
2. Improve the MyBatisProcessor to add these reflective model classes automacatilly.
3. Add a integration test to reproduce the issue (It looks like the spring framework you used in the demo).

This is an open source project and any contribution or feedback is welcome !

**Comment by 362228416** [comment]
I have updated the project demo, but I don't know much about the expansion mechanism of quarkus, so I wrote a tool class to generate reflect-config.json, and then add a line of configuration to the configuration file. If you can add it to this extension, it will be more convenient for others to use it
